### ISSUE TITLE
issue when using xarray + dask

### ISSUE THREAD

**Issue by navidcy** [ajdawson/eofs#115]
Hi there,

I'm trying to use eofs package. It seems to work OK when I use `numpy` arrays or when I __only__ use `xarray`. But I can't get around myself using it with `xarray`+`dask`.

I've reduced my dataset into something very small.

Here are 3 example notebooks...

1. [eofs with numpy](https://gist.github.com/navidcy/ef41928e5bf90561a2e1ee9a09d4e7dd)
2. [eofs with xarray](https://gist.github.com/navidcy/67636440b6f28cb30ac10063b9c64077) 
3. [eofs with xarray+dask](https://gist.github.com/navidcy/3de252f89d39a88849bdd454bfbe0602) 

@ScottWales, am I doing something wrong here? I also tried chunking ```.chunk('time'=1)``` but I still had the same issue...

**Comment by ScottWales** [comment]
The dask svd solver requires its input chunking to be 'long and thin' - it may have chunks in the time dimension, but not in the spatial dimensions. In your case your data has multiple chunks on both latitude and longitude due to your spatial binning.

**Comment by navidcy** [comment]
@ScottWales problems persist when I do that... See [this](https://gist.github.com/navidcy/b6a9b505daf68ae1aef46b8da7a1eba2) notebook.

Perhaps this is not an issue of the `eofs` but a `dask`-related issue? Or possibly issue with the way I call `dask`?

**Comment by ajdawson** [comment]
I'm closing this one as it is not clear where the problem lies, and has been a long time since the last update.
