### ISSUE TITLE
Metadata-aware solver interface to cf-python fields

### ISSUE THREAD

**Issue by sadielbartholomew** [ajdawson/eofs#118]
Hi, we've had a user feature request to our project [cf-python](https://github.com/NCAS-CMS/cf-python) for the ability to conduct EOF & rotated EOF analysis with our intrinsic data object, the ``cf-python`` field, or more precisely the 'field construct' of the CF data model (see also the [cfdm](https://github.com/NCAS-CMS/cfdm) library).

Bryan Lawrence recommended your library as a potential solution for this, notably since it appears to be open for interfacing in a way that allows for management of the underlying metadata, as demonstrated by the Iris interface module. ``cf-python`` makes use of numpy arrays under-the-hood but our philosophy & one of our core USPs is to enable data analysis that preserves CF-compliant metadata, so the standard numpy solver interface is not appropriate.

Therefore we were wondering if you'd be happy to include a module for a ``cf-python`` solver interface? If so, we'd write it (I've volunteered so I would write most, if not all, of it) & then I suggest we can put it up as a Pull Request for your review. If that sounds agreeable, please let us know any requirements/advice you might have for us to help us to develop it so it fits in as you would like, otherwise we can use the ``iris`` module as a guide. Thanks.

**Comment by ajdawson** [comment]
I'm going to close this issue now since it has been open for years I suspect it is not relevant at least in its original form. I am in the process of cleaning up this repository but available time for maintenance is short. If this is still a desirable thing to have and someone is available to work on it then please create a new issue.
