### ISSUE TITLE
Opposite signal in EOF correlation map

### ISSUE THREAD

**Issue by alinedefreitasocn** [ajdawson/eofs#120]
Hi everyone,

I'm having trouble to calculate the NAO EOF pattern. Using Eofs package example, the resultant covariance map has opposite signal (it was supposed to have negative covariance in the poles and positive in midi latitudes).
Does anyone know what's the problem?

The code used:
=======================================================
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
import numpy as np
import xarray as xr

from eofs.xarray import Eof
from eofs.examples import example_data_path

#### European/Atlantic domain (80W-40E, 20-90N).
filename = example_data_path('hgt_djf.nc')
z_djf = xr.open_dataset(filename)['z']

#### Compute anomalies by removing the time-mean.
z_djf = z_djf - z_djf.mean(dim='time')

#### latitude weights are applied before the computation of EOFs.
coslat = np.cos(np.deg2rad(z_djf.coords['latitude'].values)).clip(0., 1.)
wgts = np.sqrt(coslat)[..., np.newaxis]
solver = Eof(z_djf, weights=wgts)

#### time series and the input SLP anomalies at each grid point.
eof1 = solver.eofsAsCovariance(neofs=1)

#### Plot the leading EOF expressed as covariance in the European/Atlantic domain
clevs = np.linspace(-75, 75, 11)
proj = ccrs.Orthographic(central_longitude=-20, central_latitude=60)
ax = plt.axes(projection=proj)
ax.coastlines()
ax.set_global()
eof1[0, 0].plot.contourf(ax=ax, levels=clevs, cmap=plt.cm.RdBu_r,
                         transform=ccrs.PlateCarree(), add_colorbar=False)
ax.set_title('EOF1 expressed as covariance', fontsize=16)
plt.show()

![test_EOF](https://user-images.githubusercontent.com/13105301/100889559-2d5e2d80-34af-11eb-9e91-be5443211483.png)

=============================================================

Result was supposed to be like this:
https://www.cpc.ncep.noaa.gov/products/precip/CWlink/pna/nao_loading.html

![new nao loading](https://user-images.githubusercontent.com/13105301/100889650-4c5cbf80-34af-11eb-9412-c24b469bb107.gif)

Thanks for your time, hope this is not a silly question.

**Comment by lee1043** [comment]
Hi @alinedefreitasocn, 

The sign of an EOF is arbitrary by the nature of the EOF analysis. Please also refer @ajdawson's comment at https://github.com/ajdawson/eofs/issues/73#issuecomment-227976178. 

What I often do is multiplying -1 to the pattern and PC time series to reverse the sign if needed.

**Comment by funkpreacher** [comment]
There is no preferred sign. As the EOF are eigenvectors (of the covariance matrix), they can be normalized any way you like.

**Comment by alinedefreitasocn** [comment]
Thanks a lot @lee1043 and @funkpreacher
