### ISSUE TITLE
reconstructedField raises an AttributeError in latest Python / Xarray version

### ISSUE THREAD

**Issue by mshiv** [ajdawson/eofs#129]
When I run the following example use case
```
from eofs.xarray import Eof
solver = Eof(data) # flux is the above DataArray
reconstr = solver.reconstructedField(solver.neofs)
```
The reconstructedField method call raises an AttributeError, pointing to the following section of the code in `/lib/python3.10/site-packages/eofs/standard.py` within `reconstructedField`:

```
# Determine how the PCs and EOFs will be selected.
if isinstance(neofs, collections.Iterable):
            modes = [m - 1 for m in neofs]
        else:
            modes = slice(0, neofs)
```
Error raised: `AttributeError: module 'collections' has no attribute 'Iterable'`

It looks like usage of `collections.Iterable` has been deprecated, being refactored into a second-level module for "abstract base classes" (a similar issue raised [here](https://stackoverflow.com/questions/53978542/how-to-use-collections-abc-from-both-python-3-8-and-python-2-7/53978543#53978543)). 

Changing the above to
```
# Determine how the PCs and EOFs will be selected.
if isinstance(neofs, collections.abc.Iterable):
            modes = [m - 1 for m in neofs]
        else:
            modes = slice(0, neofs)
```
solved the issue for now.

**Comment by ajdawson** [comment]
Closed by #130.
