### ISSUE TITLE
Python collection issue with reconstructedField()

### ISSUE THREAD

**Issue by jalder-usgs** [ajdawson/eofs#131]
Hello, I am using 1.4.0 of the API with Python 3.10.4 (numpy 1.22.3) and am having problems with eofs.standard.reconstructedField(). It gives the following error:

`Traceback (most recent call last):
  File "/Users/alderj/code/Python/EOFs/Osman_EOF.py", line 33, in <module>
    reconstruction = solver.reconstructedField([1,2])
  File "/Users/alderj/miniconda3/envs/IDLPython/lib/python3.10/site-packages/eofs/standard.py", line 638, in reconstructedField
    if isinstance(neofs, collections.Iterable):
AttributeError: module 'collections' has no attribute 'Iterable'`

A quick google indicates collections.Iterable is deprecated. Is there a work around? I'd really like to be able to add PC1 and PC2 in the original data units.

**Comment by ajdawson** [comment]
Try using the master branch it has the fix in https://github.com/ajdawson/eofs/commit/416ea0c135485ddd2cdf8e6d2b9f51a4d1cddc29

**Comment by ajdawson** [comment]
I believe this fix should be in 1.4.1
