### ISSUE TITLE
conda release update needed

### ISSUE THREAD

**Issue by lee1043** [ajdawson/eofs#147]
@ajdawson thank you for the new version release!

Would you mind updating conda-forge feedstock as well so the updated version can be released through the conda as well?
 
I think this can be done by merging the below pull request at conda-forge feedstock:
https://github.com/conda-forge/eofs-feedstock/pull/11
 
which then new version will be shown on this page:
https://anaconda.org/conda-forge/eofs

**Comment by ajdawson** [comment]
Please have some patience. Maintaining this software is not part of my job, and is not a top priority for my time. It may take longer than a few hours to progress everything through to deployment!

**Comment by lee1043** [comment]
@ajdawson I totally understand, and I didn't intend to pressure. I just wanted to leave a note for record. I appreciate your volunteer work for maintaining this software.
