### ISSUE TITLE
Use of deprecated np.product

### ISSUE THREAD

**Issue by kafitzgerald** [ajdawson/eofs#151]
As of version 1.25.0 [np.product was deprecated](https://numpy.org/doc/stable/release/1.25.0-notes.html#deprecations) in favor of np.prod.  

There are few uses of this in eofs.

**Comment by kafitzgerald** [comment]
I was going to pull together a quick PR, but it looks like [someone beat me to it](https://github.com/ajdawson/eofs/pull/148).

**Comment by g-voelker** [comment]
Unfortunately, #148 isn't merged, yet, and now breaks the `eofs` package as `numpy.product` was dropped. :-(

**Comment by lee1043** [comment]
I encountered the same issue, and curious to know if there is any plan for merging PR #148.

**Comment by ajdawson** [comment]
Hi @kafitzgerald, @g-voelker, @lee1043. Sorry for not getting to this sooner. I have published a v2.0.0 release that resolves these issues. Thanks a lot for contributing, it is appreciated.
