### ISSUE TITLE
Time coord in iris cube - name is hardcoded as 'time'

### ISSUE THREAD

**Issue by SimonPeatman** [ajdawson/eofs#68]
I have an Iris cube with a time dimension co-ordinate whose `coord.name()` is `'t'`.  When trying to create a solver it crashes because the code assumes time dimensions must be called `'time'`.  This is true for univariate and multivariate solvers.

I can work around this by setting `coord.standard_name = 'time'` on all my cubes before creating EOFs, but the eofs package itself could allow for any name by doing something like `time_name = cube.coord(axis='T').name()`.

**Comment by ajdawson** [comment]
Agreed, this could be more flexible.

**Comment by ajdawson** [comment]
Fixed on master, will be in the next release (v1.2.0).
