### ISSUE TITLE
Eog weights bug

### ISSUE THREAD

**Issue by lee1043** [ajdawson/eofs#73]
Hi there, 

I've learned that sometimes giving weights='coslat' or 'area' option in Eof reverses sign (positive to negative or vise versa), looks like a bug.. (It is weird that not always but for some specific case.. no idea why..) According to the [interface description](http://ajdawson.github.io/eofs/api/eofs.cdms.html#module-eofs.cdms), it looks like weighting is square-root so should not have any effect on sign, but turning off those weight function bring back to original sign.. Do you have any idea? I have some figures can show if you want. 

I am testing with UV-CDAT implemented version, and had no chance to test the conda version yet.

**Comment by ajdawson** [comment]
Hi @lee1043. This is not a bug, but a reflection of the fact that the sign of an EOF is arbitrary (it is just an eigenvector really). By changing the weights, the input into the algorithm that computes the eigenvectors is changed, and the sign of the resulting eigenvectors may flip. You will also note that when the sign of your EOF has been changed, the sign of the corresponding PC time series has also changed.

The quantity that is invariant (in relation to the sign of the EOF) is the product of the EOF and its corresponding time series. As long as both the EOF and the PC change sign, this product remains unchanged in sign. For the purposes of displaying EOFs and attaching some physical meaning to them, or comparing them to EOFs computed from other inputs, it is therefore perfectly valid to multiply an EOF (and its corresponding PC) by -1 to change the sign.

**Comment by lee1043** [comment]
@ajdawson Thank you for clarifying!
