### ISSUE TITLE
Can I get variance fraction from projected field?

### ISSUE THREAD

**Issue by lee1043** [ajdawson/eofs#79]
Hello, 

Thanks to your effort on this package, I am using this for develop climate model evaluation tool. I could have fraction of variance using `solver.varianceFraction()`, but I am wondering if I can get the fraction but from projected field. 

I've used below to project arbitrary field to solver and gained pcs of projected field:
`pcs_of_projected_field = solver.projectField(field_to_be_projected,neofs=eofn,eofscaling=1)`

But couldn't find way to have its fraction of variance. Does EOFs have function to do this efficiently?

Thanks for your attention.

**Comment by ajdawson** [comment]
The variance fractions reported by `Eof.varianceFraction` are just the scaled eigenvalues (scaled so that they sum to 1). The eigenvalues are computed whilst computing the EOFs, so we get them for free so to speak. There is no functionality built in to compute the variance fraction of pseudo-PCs.

**Comment by lee1043** [comment]
Got it. Thank you for clarifying, I appreciate that.
