### ISSUE TITLE
How to obtain the measure of the percent variance explained by each mode?

### ISSUE THREAD

**Issue by vic1309** [ajdawson/eofs#84]
e.g. Mode 1 represents 45%, mode 2 represents 13% and so on.

Thanks!

**Comment by ajdawson** [comment]
You are looking for the [varianceFraction()](http://ajdawson.github.io/eofs/api/eofs.standard.html#eofs.standard.Eof.varianceFraction) method. It returns the fractional variance explained by each mode (in the range 0 to 1, multiply by 100 to get the percentage variance explained).
