### ISSUE TITLE
Potential issue with MKL 2018

### ISSUE THREAD

**Issue by lee1043** [ajdawson/eofs#90]
Hi @ajdawson , 

I am reporting a potential issue with recent version of MKL.

My code is using eofs in it, and it used to work well in my environment. But one day it stopped working when I upgraded the environment. 

The error was coming from `standard.py`, returning runningtime overflow error or DLASCL parameter error ([like this](https://github.com/statsmodels/statsmodels/issues/3596)) from [```self._L = Lh * Lh / normfactor```](https://github.com/ajdawson/eofs/blob/b31511fa5957793cdc356c28cd257f9fc23ff967/lib/eofs/standard.py#L166).

I learned that my issue was able to be solved by downgrading my ```mkl``` version from 2018 to 2017 as below:

```>> conda install mkl=2017.0.3```

```
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /export/lee1043/anaconda2/envs/pmp_nightly:

The following packages will be DOWNGRADED:

    mkl:   2018.0.0-hb491cac_4   --> 2017.0.3-0   
    numpy: 1.13.1-py27hd1b6e02_2 --> 1.13.1-py27_0
``` 

Not sure this would be issue for others as well, but it would be great if this could be checked. Sharing this for your interest. 

Thanks.

**Comment by ajdawson** [comment]
I don't have 2018 MKL available to test. Are the eigenvalues very large in your case? Perhaps this can be mitigated by changing the order of operations like:

```python
self._L = Lh * (Lh / normfactor)
```

Can you test this approach?

**Comment by ajdawson** [comment]
I cannot reproduce this. If this is still a problem and you can provide a self-contained example to demonstrate the problem then feel free to re-open this.
