### ISSUE TITLE
Multivariate EOFs

### ISSUE THREAD

**Issue by bonfils2** [ajdawson/eofs#97]
Hello,
Thank you so much for creating this code. I have a question: how do you normalize the input data before applying Multivariate EOFs? In addition, can you disable this option (so we could use our own normalization criterion)? I am looking at the code but cannot find where the normalization process occurs. Many thanks!

**Comment by ajdawson** [comment]
Hi @bonfils2 - There is no normalization in the library, you have to do it yourself. One approach is to standardize each anomaly field (divide by its standard deviation) before computing the EOFs. You should refer to the scientific literature for methodological guidance.

**Comment by bonfils2** [comment]
Hi @ajdawson, That sounds good, thank you very much for the information!
