### ISSUE TITLE
Support for ensemble data

### ISSUE THREAD

**Issue by thomascrocker** [ajdawson/eofs#98]
Hi there, I've just got started using the eofs package for analysis of some forecast model data. Really appreciate the functionality of the package and has saved me a lot of time already.

The model I'm working with is an ensemble based system, so ideally for the purposes of the analysis I'd like to treat each individual ensemble as an extra set of samples on the time dimension. (e.g. if I have 12 ensembles over 100 time points, on an x by y lat long grid, I end up computing eofs of 1200 time points on my x, y grid)
My data is stored in iris cubes.
Are there any plans to add support for this? If not I'm happy to *try* adding it to the source myself if I can find the time. Any suggestions on the best approach would be appreciated.
Cheers,
Tom

**Comment by ajdawson** [comment]
This should already work as expected if all your ensemble members are in the same cube (i.e. with a realisation coordinate). Did you try it and get an error message? If so please post the full traceback along with the example code here.

**Comment by thomascrocker** [comment]
My cube has realization as the first co-ordinate, (time as the second) and the code stops with an error that time must be first.
If I reorder the data so that time is the first dimension, the code executes, but then (in the case of my example of 12 ensembles over 100 time points) I end up with 100 3 dimensional eofs (i.e. realization, lat, long). When, what I actually want is 1200 eofs (100 time points * 12 ensembles) over the 2 dimensions of lat, long. I think these two things are different, although I'll concede it's been a while since I worked with Eof analysis, so I may have misunderstood something. Essentially I don't want the ensembles to be treated as an extra dimension, I just want them to be considered as extensions of the time dimension. This is easy to do if I just work with the underlying numpy array, but a bit more of a faff as an iris cube.

**Comment by ajdawson** [comment]
Ah sorry I misunderstood. No there is no support for doing this automatically, and I don't plan on adding specific support for this. Since you want to treat realization as if it were the same as time you'd be better off handling the reshaping of the cube yourself before passing the resulting cube to eofs to generate 2d EOFs.

**Comment by thomascrocker** [comment]
No problem. I'll just work with the underlying numpy array and it's fairly straightforward. Doing it with cubes is not really possible (I think) as iris will not allow the ensembles to be stacked into the time dimension as then the time co-ordinate would be non monotonic, which isn't allowed for a dim coord.
