### ISSUE TITLE
reconstructedField

### ISSUE THREAD

**Issue by daizhouchiwang** [ajdawson/eofs#99]
Hi,

I have used the eofs reconstructedField() function to reconstructing the matrix that decomposed by Eof, but  I found that even the neofs is setted as the maximum, I still cannot get the original dataset. I check through out the code, and found that the center value haven't be added back to the reconstruced dataset. Could your help me to make sure that?

```python
# This is the code that I used to do the simple test
import numpy as np
import matplotlib.pyplot as plt
from eofs.standard import Eof

a = np.random.randint(-10,10,(10,20))
solver = Eof(a)
reconstructed_data = solver.reconstructedField(solver.neofs)
plt.scatter(a.reshape(-1),reconstructed_data.reshape(-1))
plt.grid()
plt.show()

plt.scatter(a.reshape(-1),(reconstructed_data+a.mean(axis=0)).reshape(-1))
plt.grid()
plt.show()
```

**Comment by ajdawson** [comment]
I would recommend always removing the mean yourself before passing the array to the solver, the automatic removal is more of a convenience thing. For that reason the subtracted mean is deliberately not stored and added back when reconstructing a field.
